version: '3.9'

services:
  app:
    build: .
    container_name: digital_hoteis
    ports:
      - "8088:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MYSQL_HOST: mysql:3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql
    volumes:
      - ./src/main/resources/application.properties:/app/application.properties

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_hoteis
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3308:3306"
