version: '3.8'

services:
  digital_hoteis:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    depends_on:
      - mysqlserver
    networks:
      - mynetwork

  mysqlserver:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=digital_hoteis
      - MYSQL_PASSWORD=digital_hoteis
      - MYSQL_DATABASE=digital_hoteis
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - mynetwork

volumes:
  mysql_data:
  mysql_config:

networks:
  mynetwork:
    driver: bridge
